spring.application.name=RocksdbEE
app.file.input-dir=./data/incoming
app.file.processed-dir=./data/processed
app.scheduler.fixed-delay=30000
logging.level.org.apache.kafka.clients.producer=DEBUG
app.file.db-path=./data/rocksdb
app.rocksdb.use-batch=true
app.rocksdb.batch-size=1000
app.scheduler.cleanup-cron=0 * * * * *